integratedTest/urls.py
from django.urls import path

from . import views

app_name = 'integratedTest'
urlpatterns = [
    path('', views.index, name='index'),
    path('addCase/', views.addTestCase, name='addCase'),    
    #path('addCaseGetDir/', views.addCaseGetDir, name='addCaseGetDir'),
    path('addProject/', views.AddProjectView.as_view(), name='addProject'),    
    path('addCaseSubmit/', views.addCaseSubmit, name='addCaseSubmit'),    
    path('addInstance/', views.addInstance, name='addInstance'),
    path('addInstanceForCICD/', views.AddInstanceForCICDView.as_view(), name='addInstanceForCICD'),
    path('addInstanceSubmit/', views.addInstanceSubmit, name='addInstanceSubmit'),
    path('addSetting/', views.AddGlobalSettingView.as_view(), name='addSetting'),
    path('addSuite/', views.addSuite, name='addSuite'), 
    path('checkPythonModule/', views.checkPythonModule, name='checkPythonModule'),
    #path('cicd/', views.cicdView, name='cicd'),
    path('cloneCase/<int:pk>/', views.cloneCase, name='cloneCase'),
    path('cloneInstance/<int:pk>/', views.cloneInstance, name='cloneInstance'),
    path('cloneSetting/<int:pk>/', views.cloneGlobalSetting, name='cloneSetting'),
    path('cloneProject/<int:pk>/', views.cloneProject, name='cloneProject'),    
    path('cloneSuite/<int:pk>/', views.cloneSuite, name='cloneSuite'),
    path('configSave/<int:pk>/', views.configSave, name='configSave'),
    path('createJiraTicket/', views.createJiraTicket, name='createJiraTicket'),
    path('deleteCase/<int:pk>/', views.TestcaseDeleteView.as_view(), name='deleteCase'),   
    path('deleteInstance/<int:pk>/', views.InstanceDeleteView.as_view(), name='deleteInstance'), 
    path('deleteInstCICD/<int:pk>/', views.InstDelCICDView.as_view(), name='deleteInstCICD'),
    path('deleteProject/<int:pk>/', views.DeleteProjectView.as_view(), name='deleteProject'),
    path('deleteSetting/<int:pk>/', views.DeleteGlobalSetting.as_view(), name='deleteSetting'),
    path('deleteSchedule/<str:schedule_id>/', views.deleteSchedule, name='deleteSchedule'),
    path('deleteSuite/<int:pk>/', views.TestSuiteDeleteView.as_view(), name='deleteSuite'),
    path('devices/', views.devicesView, name='devices'),
    path('displayLog/<int:pk>/', views.displayLog, name='displayLog'),
    path('editCase/<int:pk>/', views.editCase, name='editCase'),
    path('editCaseSubmit/<int:pk>/', views.editCaseSubmit, name='editCaseSubmit'),
    path('editConfig/<int:pk>/', views.editConfig, name='editConfig'),
    path('editProject/<int:pk>/', views.EditProjectView.as_view(), name='editProject'),
    path('editSchedule/<str:schedule_id>/', views.editSchedule, name='editSchedule'),
    path('editSetting/<int:pk>/', views.EditGlobalSettingView.as_view(), name='editSetting'),
    path('editSuite/<int:pk>/', views.editSuite, name='editSuite'), 
    path('fakeRunInstance/<int:instance_id>/', views.fakeRunInstance, name='fakeRunInstance'),    
    path('globalsetting/', views.listGlobalSetting, name='globalsetting'),
    path('help/', views.helpView, name='help'),
    path('highlightLogKey/', views.highlightLogKey, name='highlightLogKey'),
    path('instance_cicd/', views.instance_cicd, name='instance_cicd'),    
    path('jiraSubmit/', views.jiraSubmit, name='jiraSubmit'),
    path('projects/', views.projectsView.as_view(), name='projects'),
    path('reportCompare/<int:pk>/', views.reportCompare, name='reportCompare'),
    path('reportDisplayKey/<int:pk>/', views.reportDisplayKey, name='reportDisplayKey'),
    path('refreshBranchInfo/<int:pk>/', views.refreshBranchInfo, name='refreshBranchInfo'),
    path('reportBug/', views.reportBug, name='reportBug'),
    path('runInstance/<int:instance_id>/', views.runInstance, name='runInstance'),
    path('runInstanceCICD/', views.runInstanceCICD, name='runInstanceCICD'),
    path('sandbox/', views.sandboxView, name='sandbox'),   
    path('scheduled_list/', views.scheduled_list, name='scheduled_list'),
    path('scheduler/<int:pk>/', views.scheduleInstanceView, name='scheduler'), 
    path('schedulerSubmit/<int:pk>/', views.afterScheduleSubmited, name='schedulerSubmit'),
    path('selBranch/<int:pk>/', views.selBranch, name='selBranch'),    
    path('selTestSet/<int:pk>/', views.selTestSet, name='selTestSet'),
    path('settings/', views.settings, name='settings'),
    path('SubmitTestSet/', views.SubmitTestSet, name='SubmitTestSet'),
    path('submitBranchSelect/', views.submitBranchSelect, name='submitBranchSelect'),
    path('suiteSubmit/', views.suiteSubmit, name='suiteSubmit'),   
    path('sysclone/', views.sysclone, name='sysclone'),    
    path('syscl_submit/', views.syscl_submit, name='syscl_submit'),
    path('test/', views.testView, name='test'),
    path('testcase/', views.testCase, name='testCase'),    
    path('testset/', views.testset, name='testset'),
    path('testsetSubmit/', views.testsetSubmit, name='testsetSubmit'),
    path('testsuite/', views.testSuite, name='testSuite'),
    path('upload/', views.uploadScript, name='upload'),
    path('uploadviewf/', views.uploadScriptViewf, name='uploadviewf'), 
    path('viewConfig/<int:pk>/', views.viewConfig, name='viewConfig'),
    path('viewFile/', views.viewFile, name='viewFile'),
    path('viewReport/<int:pk>/', views.viewReport, name='viewReport'),
    path('viewReportDetail/<int:pk>/', views.viewReportDetail, name='viewReportDetail'),    
]

test_me/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [     
    path('', include('integratedTest.urls'), name="main"),
    #path('admin/', admin.site.urls),
    #re_path(r'^static/(?:.*)$', serve, {'document_root': settings.STATIC_ROOT, })
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

integratedTest/models.py
from django.db import models
from django.db.models import UniqueConstraint
from django.core.validators import validate_comma_separated_integer_list
import datetime
from django.utils import timezone

PROJNAME_CHOICES = (
        ('ROMA', 'ROMA'), 
        ('PDK','PDK'),
        ('PMIC','PMIC'),
        ('OTHER','OTHER')
)

TEST_TYPE_CHOICES = (
        ('integrated_test', 'integrated_test'), 
        ('system_test','system_test'),           
        ('API_test', 'API_test'),
        ('module_test', 'module_test'), 
        ('selenium_test', 'selenium_test'),
        ('for_demo', 'for_demo'),
        ('others', 'others'),
)

MODULE_CHOICES = (        
        ('h5_composer','h5_composer'),           
        ('training', 'training'),
        ('pkl2h5', 'pkl2h5'),
        ('predict', 'predict'), 
        ('segmentation', 'segmentation'),
        ('augmentation', 'augmentation'),
        ('ppc', 'ppc'),
        ('root','root'),
        ('roma', 'roma'),    
        ('None', 'None')
) 

class Projects(models.Model):
    name = models.CharField(max_length=100, unique=True)
    module_list = models.CharField(max_length=1023, blank=True)
    created_by = models.CharField(max_length=100, default = "Wason")     
    create_datetime = models.DateTimeField("Created on", auto_now = True)    

class TestCase(models.Model):
    EXECUTABLE_TYPE_CHOICES = (
        ('py_script', 'py_script'),
        ('shell', 'shell'),
        ('others', 'others'),
    )       
    name = models.CharField(max_length=200, unique=True)
    executable = models.CharField(max_length=200, default = "")
    parameter_list = models.TextField(blank=True, default = "")
    executable_type = models.CharField(max_length=100, choices = EXECUTABLE_TYPE_CHOICES, default = "py_script")    
    project_name = models.CharField(max_length=100)
    module_name = models.CharField(max_length=100)    
    created_by = models.CharField(max_length=100, default = "")     
    create_datetime = models.DateTimeField("testcase created on", auto_now = True)
    def save(self, *args, **kwargs):
        print("\n\n\nTestCase self(new) :")
        print(self.name, " ", self.executable, " ", self.parameter_list)
        print(self.executable_type, " ", self.project_name, " ", self.module_name)
        if self.pk:
           obj = TestCase.objects.get(pk=self.pk)
           print("\n\n\nTestCase obj(old) :")
           print(obj.name, " ", obj.executable, " ", obj.parameter_list)
           print(obj.executable_type, " ", obj.project_name, " ", obj.module_name)           
           if not self.executable and obj.executable:
               self.executable = obj.executable
        
        super().save(*args, **kwargs)
    class Meta:
        ordering = ['-create_datetime']
        
class TestSuite(models.Model):    
    name = models.CharField(max_length=200, unique=True)
    test_type = models.CharField(max_length=200, choices = TEST_TYPE_CHOICES, default = "integrated_test") 
    test_case_list = models.CharField(max_length=200, default = "") 
    project_name = models.CharField(max_length=100, default="OTHER")
    created_by = models.CharField(max_length=100, default = "Wason")     
    create_datetime = models.DateTimeField("TestSuite created on", auto_now = True)
    def cases_as_list(self):
        return self.test_case_list.split(',')
    class Meta:
        ordering = ['-create_datetime']

def validate_progress(value):
    if value < 0 or value > 100:
        raise ValidationError(
            _('%(value)s not a valid progress value [0, 100]'),
            params={'value': value},
        )
        
class TestInstance(models.Model):
    name = models.CharField(max_length=200, unique=True)    
    testsuite = models.CharField(max_length=200)
    test_status = models.CharField(max_length=200, default = "Not Run")
    progress = models.IntegerField(default = 0, validators=[validate_progress])    
    test_result = models.CharField(blank=True, max_length=200, default = "N/A")
    command_list = models.CharField(blank=True, max_length=2048, default = "")
    created_from_web = models.BooleanField(default = True)
    created_by = models.CharField(max_length=100, default = "Wason")
    last_touched = models.DateTimeField("last run date", default = timezone.now)
    last_run = models.DateTimeField("last run date", null=True)    
    create_datetime = models.DateTimeField("instance created on", auto_now_add = True)
    class Meta:
        ordering = ['-last_run', '-create_datetime']

            
class TestReport(models.Model):
    name = models.CharField(max_length=200, unique=True)    
    testinstance = models.ForeignKey(TestInstance, on_delete=models.CASCADE)
    test_detail = models.CharField(blank=True, max_length=1023, default = "")    
    test_result = models.CharField(blank=True, max_length=200, default = "Pass")
    log_path = models.CharField(blank=True, max_length=1023, default = "")
    create_datetime = models.DateTimeField("instance created on", auto_now = True)
    def detail_as_list(self):
        return self.test_detail.split(',')
    class Meta:
        ordering = ['-create_datetime']
        
class ActiveTestSet(models.Model):       
    name = models.CharField(max_length=200)
    instance_id = models.IntegerField(default = -1)
    case_index_in_instance = models.IntegerField(default = -1)
    full_path = models.CharField(max_length=500)
    config_fname = models.CharField(max_length=200, default = "")
    

#Remember last used things
class RecentlyUsedSetting(models.Model):       
    project_name = models.CharField(max_length=100, default = "")
    repo_path = models.CharField(max_length=511, default = "")
    path_sel = models.CharField(max_length=511, default = "")
    exe_sel= models.CharField(max_length=128, default = "")
    create_datetime = models.DateTimeField(auto_now = True)

#Used for supervise whether one instance is running.
#Fake run is permitted when a true run isn't finished.
class RunningTable(models.Model):
    class Meta:
        UniqueConstraint(fields = ['instance_id', 'is_true_run'], name = 'constraint_name')
    instance_id = models.IntegerField()
    project_name = models.CharField(max_length=100, default = "ROMA")
    is_running = models.BooleanField(default = False)
    is_true_run = models.BooleanField(default = True)
    start_datetime = models.DateTimeField(null=True, blank=True)
    complete_datetime = models.DateTimeField(null=True, blank=True)
    fake_run_result = models.CharField(max_length=1024, default = "")
    create_datetime = models.DateTimeField(auto_now = True)

    
class GlobalSetting(models.Model):       
    name = models.CharField(max_length=200, default="noname", unique=True)
    hostname = models.CharField(max_length=200, default="unknownhost")
    ostype = models.CharField(max_length=200, default="unknownos")
    project_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default = False)
    user = models.CharField(max_length=100, default = "")
    #def save(self, *args, **kwargs):
        #if self.__class__.objects.count():
            #self.pk = self.__class__.objects.first().pk
        #super().save(*args, **kwargs)

 
class Repository(models.Model):
    project_name = models.CharField(max_length=200, default="")
    module_name = models.CharField(max_length=100, default="None")
    gitserver_msg = models.CharField(max_length=200, default="")
    branch_msg = models.CharField(max_length=200, default="")
    revision_hash = models.CharField(max_length=200, default="")    
    create_datetime = models.DateTimeField(auto_now = True)

def upload_to(instance, filename):
    #print(instance.project_name+"/"+filename)
    return (instance.project_name+"/"+filename) 
    
class Document(models.Model):
    #docfile = models.FileField(upload_to='documents/%Y/%m/%d')
    docfile = models.FileField(upload_to=upload_to)
    project_name = models.CharField(max_length=100)
    

def get_objs_else_None(modelName, **kwargs):
    try:
        return modelName.objects.filter(**kwargs)
    except modelName.DoesNotExist:
        return None

def get_obj_else_None(modelName, **kwargs):
    try:
        return modelName.objects.get(**kwargs)
    except modelName.DoesNotExist:
        return None    

integratedTest/forms.py
from .models import TestCase, GlobalSetting, TestSuite, TestReport, TestInstance, PROJNAME_CHOICES, Projects
from django import forms


class TestCaseUpdateForm(forms.ModelForm):
    class Meta:
        model = TestCase
        fields = ( 'name', 'executable', 'parameter_list', 'executable_type', 'project_name', 'module_name', 'created_by')
        

class TestInstanceForm(forms.ModelForm):
    class Meta:
        model = TestInstance
        fields = ( 'name', 'testsuite', 'created_by', 'created_from_web')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'mytextinputclasssmall'}),            
            'created_by': forms.TextInput(attrs={'class': 'mytextinputclasssmall'}),
        }
        
class GlobalSetUpdateForm(forms.ModelForm):
    class Meta:
        model = GlobalSetting
        fields = ( 'name', 'hostname', 'ostype', 'user', 'is_active', 'project_name' )

class TestSuiteForm(forms.ModelForm):
    class Meta:
        model = TestSuite
        fields = ( 'name', 'test_case_list', 'project_name', 'test_type', 'created_by' )

class TestReportForm(forms.ModelForm):
    class Meta:
        model = TestReport
        fields = ( 'name', 'test_detail', 'test_result', 'log_path' )

class ProjectsForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ( 'name', 'module_list', 'created_by' )
        
class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()
    
class DocumentForm(forms.Form):
    project_name = forms.CharField(
        label='Please select a project name for your script', 
        widget=forms.Select(choices=PROJNAME_CHOICES)
    )
        
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )


    
    

integratedTest/templates/integratedTest/globalsetting_form.html
<form id="id_save" method="post">
{% csrf_token %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
<h1 >Add Gloabl Setting  ({{hostname}}, {{os}}):</h1>
<table> 
  <tr>
      <th>Name:</th>
      
      
  </tr>
  <tr>
  <td><input type="text" id="id_name" name="name" value="setting_" required></td>
  
  </tr>
 
  

  <tr>
  
  <th>user:</th>
  <th>is_active:One active for use for each project on each server.</th>
  </tr>
  <tr>
  
  <td><input type="text" id="id_user" name="user" required></td>  
  <td>
    <input type="checkbox" id="id_is_active" name="is_active" >
  </td>
  </tr>
  
  <tr>
    <th>project_name:</th>  
    <th>Host Name</th>
    <th>OS</th> 
  </tr>
  <tr>
    <td> 
      <select name="project_name" id="id_project_name" >  
        {%for item in projnames %}
          {%if item == name_0 %}
            <option value={{item}} selected>{{item}}</option>
          {%else%}
            <option value={{item}}>{{item}}</option>      
          {%endif%}
        {%endfor%}
      </select>
    </td> 
    <td>
        {{hostname}}
      </td>
      <td>
        {{os}}
    </td>  
  </tr>
  
</table> 
  <input type="hidden" id="id_hostname" name="hostname" value="{{hostname}}">
  <input type="hidden" id="id_ostype" name="ostype" value="{{os}}">
  <input form="id_save" type="submit" value="Save">

</form>

  <form id="id_cancel" action="{% url 'integratedTest:globalsetting'%}" method="post">
    {% csrf_token %}
    <input form="id_cancel" type="submit" formnovalidate value="Cancel">   
  </form>



  

integratedTest/templates/integratedTest/globalsetting_update_form.html
<form id="id_save" method="post">
{% csrf_token %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
<h1>Update Gloabl Setting  ({{hostname}}, {{os}}):</h1> 
<table>
  <tr>
      <th>Name:</th>      
      
  </tr>
  <tr>
  <td><input type="text" id="id_name" name="name" value = "{{my_setting.name}}" required></td>
  </tr>
  
  
  
  <tr>  
      <th>user:</th>
      <th>is_active:</th>
  </tr>
  <tr>
      <td><input type="text" id="id_user" name="user" value = "{{my_setting.user}}" required></td>
      <td> 
          {%if my_setting.is_active%}
            <input type="checkbox" id="id_is_active" name="is_active" checked>
                
              {%else%}
                <input type="checkbox" id="id_is_active" name="is_active" >
          {%endif%}
      </td>
  </tr>
  
  <tr>
      <th>project_name</th>
      <th>Host Name</th>
      <th>OS</th>      
  </tr>
  <tr>
      <td>
          <select name="project_name" id="id_project_name" required> 
          {%for item in projnames %}
              {%if my_setting.project_name == item %}
                <option value={{item}} selected>{{item}}</option>
              {%else%}
                <option value={{item}}>{{item}}</option>      
              {%endif%}
          {%endfor%}
          </select>  
      </td>
      <td>
        {{hostname}}
      </td>
      <td>
        {{os}}
      </td>
  </tr>
  
</table>
  <input type="hidden" id="id_hostname" name="hostname" value="{{hostname}}">
  <input type="hidden" id="id_ostype" name="ostype" value="{{os}}">
    
  <input form="id_save" type="submit" value="Update">
</form>

  <form id="id_cancel" action="{% url 'integratedTest:globalsetting'%}" method="post">
    {% csrf_token %}
    <input form="id_cancel" type="submit" formnovalidate value="Cancel">   
  </form>

  

integratedTest/templates/integratedTest/navigation.html
{% load static %}

<div id="id_topnav" class="topnav">
  <a  href="{% url 'integratedTest:index'%}" title="Test instance management.">Home</a>
  <a  href="{% url 'integratedTest:instance_cicd'%}" 
    title="Gitlab CICD pipeline triggered test instance running.">InstanceFromCICD</a>
  <a  href="{% url 'integratedTest:testSuite'%}" 
    title="Test suite defining, modifying, cloning and deleting.">Test Suite</a>
  <a  href="{% url 'integratedTest:testCase'%}"
    title="Test case defining, modifying, cloning and deleting.">Test Case</a>
  <a  href="{% url 'integratedTest:projects'%}"
    title="Project defining, cloning and deleting.">Project</a>
  <a  href="{% url 'integratedTest:scheduled_list'%}"
    title="Test instance scheduled to run">Scheduled List</a>  
  <!--<a  href="{% url 'integratedTest:testset'%} "title="Create Test Set">Test Set</a>-->
  <a  href="{% url 'integratedTest:sysclone'%}"
    title="Moving test cases between testMe servers by json file">System Clone</a>
  <!--<a  href="{% url 'integratedTest:devices'%}" title="Devices Settings">Devices</a>-->
  <a  href="{% url 'integratedTest:settings'%}"
    title="Settings like email list etc.">Settings</a>
  <a  href="{% url 'integratedTest:reportBug'%}"
    title="Create a Jira ticket.">Report Bug</a>
  <!--<a  href="{% url 'integratedTest:upload'%}">Upload Test Script</a>-->
  <!--<a  href="{% url 'integratedTest:sandbox'%}">Sandbox</a>-->
  <!--<a  href="{% url 'integratedTest:globalsetting'%}">Global Settings</a>-->
  <a  href="{% url 'integratedTest:help'%}">Help</a>
  <!--<a  href="{% url 'integratedTest:test'%}">Test</a>-->  
</div>

integratedTest/templates/integratedTest/viewreport_form.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'main/folder_view.css' %}">
<script src="https://code.jquery.com/jquery-3.5.0.min.js"></script>

<h1 >Reports for {{instance_name}}</h1>
{% if err %}        
    <b style="color:red">{{err}}</b>
{% endif %}
<p><table>
  <td><b>Select Reports:</b>
  <form id="id_form_select" method="post" action="{% url 'integratedTest:viewReport' instance_id%}" >
      {% csrf_token %}
      <select name="report_list_select" id="id_report_list_select" >
      {%for filename in filenamelist %}
      {%if filename == fname_to_display %}
       <option value="{{filename}}" selected>{{filename}}</option>  
      {%else %}
       <option value="{{filename}}" >{{filename}}</option>
      {%endif %} 
      {%endfor %}  
      </select>  
      </form>
  </td>
  
  <td><b>Compare With</b></td>
  
  <form action="{% url 'integratedTest:reportCompare' instance_id %}" method="post">
  {% csrf_token %} 
  <td><ul id="id_running">
      
      <select name="compare_with" id="id_compare_with" >
          {%for filename in filenamelist %}
          {%if filename != fname_to_display %}
           <option value="{{filename}}" >{{filename}}</option> 
          {%endif %} 
          {%endfor %}  
      </select>
    
  </ul></td>
  
      <td><select name="compare_by" id="id_compare_by" >
        <option value="compareLog" selected>compareLog</option>
        <option value="compareYaml" >compareYaml</option>
        <option value="comparePkl" disabled>comparePkl</option>
        <option value="compareOther" disabled>compareOther</option>
      </td>
      <td>
        <input type="hidden" name="instance_name" value="{{instance_name}}">
        <input type="hidden" name="suite_name" value="{{suite_name}}">
        <input type="hidden" name="project_name" value="{{project_name}}">
        <input type="hidden" name="inst_name" value="{{instance_name}}">
        <input type="hidden" name="left_name" value="{{fname_to_display}}">
        <input type="submit" value="Compare">
        </td>        
    </form>
  
  </table>
  
    {% if from_web %}
        <form action="{% url 'integratedTest:index'%}" method="post">
        {% csrf_token %} 
            <input type="submit" value="BackToHome">    
        </form>
    {% else %} 
        <form action="{% url 'integratedTest:instance_cicd'%}" method="post">
        {% csrf_token %} 
            <input type="submit" value="BackToHome">    
        </form>
    {% endif %}
    
    <form action="{% url 'integratedTest:viewReportDetail' instance_id %}" method="post">
    {% csrf_token %} 
        <input type="hidden" name="report_root" value="{{report_dir}}">
        <input type="submit" value="DetailReport">    
    </form>
  
<table>
<tr> 
    <td>
    <b><lable for="insname">Instance Name:</lable></b></td><td>
    <div id="insname">{{rep_requested.instance_name}}</div>
    </td>
    
    <td>
    <b><lable for="suitename">Suite Name:</lable></b></td><td>
    <div id="suitename">{{rep_requested.suite_name}}</div>
    </td>
    
    <td>
    <b><lable for="runtype">Run Type:</lable></b></td><td>
    <div id="runtype"><b>{{rep_requested.runType}}</b></div>
    </td>
    
    <td>
    <b><lable for="startTotal">Start :</lable></b></td><td>
    <div id="startTotal">{{rep_requested.startTotal}}</div>
    </td>
    
    <td>
    <b><lable for="endTotal">End :</lable></b></td><td>
    <div id="endTotal">{{rep_requested.endTotal}}</div>
    </td>
    
    <td>
    <b><lable for="durTotal">Time Totally Used:</lable></b></td><td>
    <div id="durTotal">{{rep_requested.durTotal}}</div>
    </td>
    
    <td><b><lable for="log">Log:</lable></b></td><td>
    <div id="log">
    <form action="{% url 'integratedTest:displayLog' instance_id%}" method="post">
            {% csrf_token %}            
    <input type="submit" value="Log">  
    <input type="hidden" id="id_rep_name" name="rep_name" value="{{fname_to_display}}">
    <input type="hidden" id="id_suite_name" name="suite_name" value="{{rep_requested.suite_name}}">
    <input type="hidden" id="id_instance_name" name="instance_name" value="{{rep_requested.instance_name}}"> 
    <input type="hidden" id="id_project_name" name="project_name" value="{{project_name}}">            
     </form>
      </div>
      </td>
</tr>
</table>
 
 <br>
 
   <h3 >test cases:</h3>
   <p id="id_case">
   {%for cur_case in rep_requested.test_cases %}
        <table>
            <tr>
                <th>Test Case Name</th>
                <th>Branch Name</th>
                <th>Server Name</th>
                <th>Executable</th>
                <th>Parameter List</th>
                <th>Reserved</th>
            </tr>
            <tr>
                {% if cur_case  %}
                <td>{{cur_case.name}}</td>
                <td>{{cur_case.meta.branchName}}</td>
                <td>{{cur_case.meta.serverName}}</td>                
    <td><div class="div_exe" title="{{cur_case.meta.exe}}">{{cur_case.meta.exe_abr}}</div></td>
    <td><div class="my_para" title="{{cur_case.meta.para}}">{{cur_case.meta.para_abr}}</div></td>
                <td>Reserved</td>
                {% else %}
                <td>N/A</td>
                <td>N/A</td>
                <td>N/A</td>
                <td>N/A</td>  
                <td>N/A</td>
                              
                {% endif %}
            </tr>
        </table>
        <table>
            <tr>
            <th>Round</th>
            <th>Result</th>    
            <th>Error Message</th>
            <th>Start At</th>
            <th>End At</th>
            <th>Time Used</th>
            </tr>
                {% if cur_case  %}
                    {%for one_res in cur_case.results %}                
                        <tr>
                            <td>{{one_res.round}}</td>
                            <td>{{one_res.p_f}}</td>
                            <td>{{one_res.msg}}</td>        
                            <td>{{one_res.start}}</td>
                            <td>{{one_res.end}}</td>
                            <td>{{one_res.dur}}</td>
                        </tr>
                    {%endfor %}
                {% else %}
                    <tr>                    
                        <td>N/A</td>
                        <td>N/A</td>
                        <td>N/A</td>
                        <td>N/A</td>
                        <td>N/A</td>
                        <td>N/A</td>
                    </tr>
                {%endif %} 
        </table>
   {%endfor %} 
   </p>    
  <input type="hidden" id="id_fname_selected" name="fname_selected" value="">    
</p>
<br><br>
<script>

    $(document).ready(function() {    
        $('#id_form_select').on('change', function() {          
          $('#id_form_select').submit()
        });
    });
    
</script>