integratedTest/urls.py
from django.urls import path

from . import views

app_name = 'integratedTest'
urlpatterns = [
    path('', views.index, name='index'),
    path('addCase/', views.addTestCase, name='addCase'),    
    #path('addCaseGetDir/', views.addCaseGetDir, name='addCaseGetDir'),
    path('addProject/', views.AddProjectView.as_view(), name='addProject'),    
    path('addCaseSubmit/', views.addCaseSubmit, name='addCaseSubmit'),    
    path('addInstance/', views.addInstance, name='addInstance'),
    path('addInstanceForCICD/', views.AddInstanceForCICDView.as_view(), name='addInstanceForCICD'),
    path('addInstanceSubmit/', views.addInstanceSubmit, name='addInstanceSubmit'),
    path('addSetting/', views.AddGlobalSettingView.as_view(), name='addSetting'),
    path('addSuite/', views.addSuite, name='addSuite'), 
    path('checkPythonModule/', views.checkPythonModule, name='checkPythonModule'),
    #path('cicd/', views.cicdView, name='cicd'),
    path('cloneCase/<int:pk>/', views.cloneCase, name='cloneCase'),
    path('cloneInstance/<int:pk>/', views.cloneInstance, name='cloneInstance'),
    path('cloneSetting/<int:pk>/', views.cloneGlobalSetting, name='cloneSetting'),
    path('cloneProject/<int:pk>/', views.cloneProject, name='cloneProject'),    
    path('cloneSuite/<int:pk>/', views.cloneSuite, name='cloneSuite'),
    path('configSave/<int:pk>/', views.configSave, name='configSave'),
    path('createJiraTicket/', views.createJiraTicket, name='createJiraTicket'),
    path('deleteCase/<int:pk>/', views.TestcaseDeleteView.as_view(), name='deleteCase'),   
    path('deleteInstance/<int:pk>/', views.InstanceDeleteView.as_view(), name='deleteInstance'), 
    path('deleteInstCICD/<int:pk>/', views.InstDelCICDView.as_view(), name='deleteInstCICD'),
    path('deleteProject/<int:pk>/', views.DeleteProjectView.as_view(), name='deleteProject'),
    path('deleteSetting/<int:pk>/', views.DeleteGlobalSetting.as_view(), name='deleteSetting'),
    path('deleteSchedule/<str:schedule_id>/', views.deleteSchedule, name='deleteSchedule'),
    path('deleteSuite/<int:pk>/', views.TestSuiteDeleteView.as_view(), name='deleteSuite'),
    path('devices/', views.devicesView, name='devices'),
    path('displayLog/<int:pk>/', views.displayLog, name='displayLog'),
    path('editCase/<int:pk>/', views.editCase, name='editCase'),
    path('editCaseSubmit/<int:pk>/', views.editCaseSubmit, name='editCaseSubmit'),
    path('editConfig/<int:pk>/', views.editConfig, name='editConfig'),
    path('editProject/<int:pk>/', views.EditProjectView.as_view(), name='editProject'),
    path('editSchedule/<str:schedule_id>/', views.editSchedule, name='editSchedule'),
    path('editSetting/<int:pk>/', views.EditGlobalSettingView.as_view(), name='editSetting'),
    path('editSuite/<int:pk>/', views.editSuite, name='editSuite'), 
    path('fakeRunInstance/<int:instance_id>/', views.fakeRunInstance, name='fakeRunInstance'),    
    path('globalsetting/', views.listGlobalSetting, name='globalsetting'),
    path('help/', views.helpView, name='help'),
    path('highlightLogKey/', views.highlightLogKey, name='highlightLogKey'),
    path('instance_cicd/', views.instance_cicd, name='instance_cicd'),    
    path('jiraSubmit/', views.jiraSubmit, name='jiraSubmit'),
    path('projects/', views.projectsView.as_view(), name='projects'),
    path('reportCompare/<int:pk>/', views.reportCompare, name='reportCompare'),
    path('reportDisplayKey/<int:pk>/', views.reportDisplayKey, name='reportDisplayKey'),
    path('refreshBranchInfo/<int:pk>/', views.refreshBranchInfo, name='refreshBranchInfo'),
    path('reportBug/', views.reportBug, name='reportBug'),
    path('runInstance/<int:instance_id>/', views.runInstance, name='runInstance'),
    path('runInstanceCICD/', views.runInstanceCICD, name='runInstanceCICD'),
    path('sandbox/', views.sandboxView, name='sandbox'),   
    path('scheduled_list/', views.scheduled_list, name='scheduled_list'),
    path('scheduler/<int:pk>/', views.scheduleInstanceView, name='scheduler'), 
    path('schedulerSubmit/<int:pk>/', views.afterScheduleSubmited, name='schedulerSubmit'),
    path('selBranch/<int:pk>/', views.selBranch, name='selBranch'),    
    path('selTestSet/<int:pk>/', views.selTestSet, name='selTestSet'),
    path('settings/', views.settings, name='settings'),
    path('SubmitTestSet/', views.SubmitTestSet, name='SubmitTestSet'),
    path('submitBranchSelect/', views.submitBranchSelect, name='submitBranchSelect'),
    path('suiteSubmit/', views.suiteSubmit, name='suiteSubmit'),   
    path('sysclone/', views.sysclone, name='sysclone'),    
    path('syscl_submit/', views.syscl_submit, name='syscl_submit'),
    path('test/', views.testView, name='test'),
    path('testcase/', views.testCase, name='testCase'),    
    path('testset/', views.testset, name='testset'),
    path('testsetSubmit/', views.testsetSubmit, name='testsetSubmit'),
    path('testsuite/', views.testSuite, name='testSuite'),
    path('upload/', views.uploadScript, name='upload'),
    path('uploadviewf/', views.uploadScriptViewf, name='uploadviewf'), 
    path('viewConfig/<int:pk>/', views.viewConfig, name='viewConfig'),
    path('viewFile/', views.viewFile, name='viewFile'),
    path('viewReport/<int:pk>/', views.viewReport, name='viewReport'),
    path('viewReportDetail/<int:pk>/', views.viewReportDetail, name='viewReportDetail'),    
]

test_me/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [     
    path('', include('integratedTest.urls'), name="main"),
    #path('admin/', admin.site.urls),
    #re_path(r'^static/(?:.*)$', serve, {'document_root': settings.STATIC_ROOT, })
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]

integratedTest/models.py
from django.db import models
from django.db.models import UniqueConstraint
from django.core.validators import validate_comma_separated_integer_list
import datetime
from django.utils import timezone

PROJNAME_CHOICES = (
        ('ROMA', 'ROMA'), 
        ('PDK','PDK'),
        ('PMIC','PMIC'),
        ('OTHER','OTHER')
)

TEST_TYPE_CHOICES = (
        ('integrated_test', 'integrated_test'), 
        ('system_test','system_test'),           
        ('API_test', 'API_test'),
        ('module_test', 'module_test'), 
        ('selenium_test', 'selenium_test'),
        ('for_demo', 'for_demo'),
        ('others', 'others'),
)

MODULE_CHOICES = (        
        ('h5_composer','h5_composer'),           
        ('training', 'training'),
        ('pkl2h5', 'pkl2h5'),
        ('predict', 'predict'), 
        ('segmentation', 'segmentation'),
        ('augmentation', 'augmentation'),
        ('ppc', 'ppc'),
        ('root','root'),
        ('roma', 'roma'),    
        ('None', 'None')
) 

class Projects(models.Model):
    name = models.CharField(max_length=100, unique=True)
    module_list = models.CharField(max_length=1023, blank=True)
    created_by = models.CharField(max_length=100, default = "Wason")     
    create_datetime = models.DateTimeField("Created on", auto_now = True)    

class TestCase(models.Model):
    EXECUTABLE_TYPE_CHOICES = (
        ('py_script', 'py_script'),
        ('shell', 'shell'),
        ('others', 'others'),
    )       
    name = models.CharField(max_length=200, unique=True)
    executable = models.CharField(max_length=200, default = "")
    parameter_list = models.TextField(blank=True, default = "")
    executable_type = models.CharField(max_length=100, choices = EXECUTABLE_TYPE_CHOICES, default = "py_script")    
    project_name = models.CharField(max_length=100)
    module_name = models.CharField(max_length=100)    
    created_by = models.CharField(max_length=100, default = "")     
    create_datetime = models.DateTimeField("testcase created on", auto_now = True)
    def save(self, *args, **kwargs):
        print("\n\n\nTestCase self(new) :")
        print(self.name, " ", self.executable, " ", self.parameter_list)
        print(self.executable_type, " ", self.project_name, " ", self.module_name)
        if self.pk:
           obj = TestCase.objects.get(pk=self.pk)
           print("\n\n\nTestCase obj(old) :")
           print(obj.name, " ", obj.executable, " ", obj.parameter_list)
           print(obj.executable_type, " ", obj.project_name, " ", obj.module_name)           
           if not self.executable and obj.executable:
               self.executable = obj.executable
        
        super().save(*args, **kwargs)
    class Meta:
        ordering = ['-create_datetime']
        
class TestSuite(models.Model):    
    name = models.CharField(max_length=200, unique=True)
    test_type = models.CharField(max_length=200, choices = TEST_TYPE_CHOICES, default = "integrated_test") 
    test_case_list = models.CharField(max_length=200, default = "") 
    project_name = models.CharField(max_length=100, default="OTHER")
    created_by = models.CharField(max_length=100, default = "Wason")     
    create_datetime = models.DateTimeField("TestSuite created on", auto_now = True)
    def cases_as_list(self):
        return self.test_case_list.split(',')
    class Meta:
        ordering = ['-create_datetime']

def validate_progress(value):
    if value < 0 or value > 100:
        raise ValidationError(
            _('%(value)s not a valid progress value [0, 100]'),
            params={'value': value},
        )
        
class TestInstance(models.Model):
    name = models.CharField(max_length=200, unique=True)    
    testsuite = models.CharField(max_length=200)
    test_status = models.CharField(max_length=200, default = "Not Run")
    progress = models.IntegerField(default = 0, validators=[validate_progress])    
    test_result = models.CharField(blank=True, max_length=200, default = "N/A")
    command_list = models.CharField(blank=True, max_length=2048, default = "")
    created_from_web = models.BooleanField(default = True)
    created_by = models.CharField(max_length=100, default = "Wason")
    last_touched = models.DateTimeField("last run date", default = timezone.now)
    last_run = models.DateTimeField("last run date", null=True)    
    create_datetime = models.DateTimeField("instance created on", auto_now_add = True)
    class Meta:
        ordering = ['-last_run', '-create_datetime']

            
class TestReport(models.Model):
    name = models.CharField(max_length=200, unique=True)    
    testinstance = models.ForeignKey(TestInstance, on_delete=models.CASCADE)
    test_detail = models.CharField(blank=True, max_length=1023, default = "")    
    test_result = models.CharField(blank=True, max_length=200, default = "Pass")
    log_path = models.CharField(blank=True, max_length=1023, default = "")
    create_datetime = models.DateTimeField("instance created on", auto_now = True)
    def detail_as_list(self):
        return self.test_detail.split(',')
    class Meta:
        ordering = ['-create_datetime']
        
class ActiveTestSet(models.Model):       
    name = models.CharField(max_length=200)
    instance_id = models.IntegerField(default = -1)
    case_index_in_instance = models.IntegerField(default = -1)
    full_path = models.CharField(max_length=500)
    config_fname = models.CharField(max_length=200, default = "")
    

#Remember last used things
class RecentlyUsedSetting(models.Model):       
    project_name = models.CharField(max_length=100, default = "")
    repo_path = models.CharField(max_length=511, default = "")
    path_sel = models.CharField(max_length=511, default = "")
    exe_sel= models.CharField(max_length=128, default = "")
    create_datetime = models.DateTimeField(auto_now = True)

#Used for supervise whether one instance is running.
#Fake run is permitted when a true run isn't finished.
class RunningTable(models.Model):
    class Meta:
        UniqueConstraint(fields = ['instance_id', 'is_true_run'], name = 'constraint_name')
    instance_id = models.IntegerField()
    project_name = models.CharField(max_length=100, default = "ROMA")
    is_running = models.BooleanField(default = False)
    is_true_run = models.BooleanField(default = True)
    start_datetime = models.DateTimeField(null=True, blank=True)
    complete_datetime = models.DateTimeField(null=True, blank=True)
    fake_run_result = models.CharField(max_length=1024, default = "")
    create_datetime = models.DateTimeField(auto_now = True)

    
class GlobalSetting(models.Model):       
    name = models.CharField(max_length=200, default="noname", unique=True)
    hostname = models.CharField(max_length=200, default="unknownhost")
    ostype = models.CharField(max_length=200, default="unknownos")
    project_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default = False)
    user = models.CharField(max_length=100, default = "")
    #def save(self, *args, **kwargs):
        #if self.__class__.objects.count():
            #self.pk = self.__class__.objects.first().pk
        #super().save(*args, **kwargs)

 
class Repository(models.Model):
    project_name = models.CharField(max_length=200, default="")
    module_name = models.CharField(max_length=100, default="None")
    gitserver_msg = models.CharField(max_length=200, default="")
    branch_msg = models.CharField(max_length=200, default="")
    revision_hash = models.CharField(max_length=200, default="")    
    create_datetime = models.DateTimeField(auto_now = True)

def upload_to(instance, filename):
    #print(instance.project_name+"/"+filename)
    return (instance.project_name+"/"+filename) 
    
class Document(models.Model):
    #docfile = models.FileField(upload_to='documents/%Y/%m/%d')
    docfile = models.FileField(upload_to=upload_to)
    project_name = models.CharField(max_length=100)
    

def get_objs_else_None(modelName, **kwargs):
    try:
        return modelName.objects.filter(**kwargs)
    except modelName.DoesNotExist:
        return None

def get_obj_else_None(modelName, **kwargs):
    try:
        return modelName.objects.get(**kwargs)
    except modelName.DoesNotExist:
        return None    

integratedTest/forms.py
from .models import TestCase, GlobalSetting, TestSuite, TestReport, TestInstance, PROJNAME_CHOICES, Projects
from django import forms


class TestCaseUpdateForm(forms.ModelForm):
    class Meta:
        model = TestCase
        fields = ( 'name', 'executable', 'parameter_list', 'executable_type', 'project_name', 'module_name', 'created_by')
        

class TestInstanceForm(forms.ModelForm):
    class Meta:
        model = TestInstance
        fields = ( 'name', 'testsuite', 'created_by', 'created_from_web')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'mytextinputclasssmall'}),            
            'created_by': forms.TextInput(attrs={'class': 'mytextinputclasssmall'}),
        }
        
class GlobalSetUpdateForm(forms.ModelForm):
    class Meta:
        model = GlobalSetting
        fields = ( 'name', 'hostname', 'ostype', 'user', 'is_active', 'project_name' )

class TestSuiteForm(forms.ModelForm):
    class Meta:
        model = TestSuite
        fields = ( 'name', 'test_case_list', 'project_name', 'test_type', 'created_by' )

class TestReportForm(forms.ModelForm):
    class Meta:
        model = TestReport
        fields = ( 'name', 'test_detail', 'test_result', 'log_path' )

class ProjectsForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ( 'name', 'module_list', 'created_by' )
        
class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()
    
class DocumentForm(forms.Form):
    project_name = forms.CharField(
        label='Please select a project name for your script', 
        widget=forms.Select(choices=PROJNAME_CHOICES)
    )
        
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )


    
    

integratedTest/templates/integratedTest/navigator/home.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
{% include "integratedTest/navigation.html" %}
<div style="overflow-x:auto;">
<br><br>
<h3 >Home</h3>

    <h4 >Test Instance List</h4>
    {% if data_inst %}
        {% if data_inst.error %}        
            <b style="color:red">{{data_inst.error}}</b>
        {% endif %}
        {% if data_inst.command_list and not data_inst.isTrueRun%}        
            <b>command_list:<br>{{data_inst.command_list}}</b>
        {% endif %}
    {% endif %}
    <br>
    <table>
        <form action="{% url 'integratedTest:addInstance' %}" method="post">
        {% csrf_token %}
            {% if data_inst %}
                <input type="submit" value="AddInstance" style="width:120">
            {% else %}  
                <input type="submit" value="AddInstance" disabled>
                Please create a test suite first. No test suite found.
            {% endif %}    
        </form>
        <form action="{% url 'integratedTest:checkPythonModule' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="listPythonModules" style="width:120">    
        </form>
    </table>
<table >
  <tr>
    <th>Action</th>
    <th>Name</th>
    <th>Test Suite</th>    
    <th>Progress</th>
    <th>Result</th>
    <th>Report</th>
    <th>Scheduler</th>
    <th>Last Run On</th>
    <th>Created By</th>
    <th>Created On</th> 
    {% if data_inst and data_inst.inst_meta %}
        <th>Running Info</th>
    {% endif %}    
  </tr>
  
  {% if data_inst and  data_inst.test_instance %}
    {% for instance in data_inst.test_instance %}
    <tr><td>    
        
        <table>
        <tr>
        <form action="{% url 'integratedTest:fakeRunInstance' instance.id%}" method="post">
            {% csrf_token %}
                <input type="submit" value="FakeRun" style="width:100">
                <input type="hidden" id="id_sche_mode" name="sche_mode" value="interval">
                <input type="hidden" id="id_hour" name="run_hour" value=0>
                <input type="hidden" id="id_minute" name="run_minute" value=0>
            </form>
        </tr><tr>
            <form action="{% url 'integratedTest:runInstance' instance.id%}" method="post">
            {% csrf_token %}
                <input type="submit" value="Run" style="width:100">
                <input type="hidden" id="id_sche_mode" name="sche_mode" value="interval">
                <input type="hidden" id="id_hour" name="run_hour" value=0>
                <input type="hidden" id="id_minute" name="run_minute" value=0>
            </form>
        </tr><tr>
            <form action="{% url 'integratedTest:refreshBranchInfo' instance.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="refreshInfo" style="width:100">    
            </form>
        </tr><tr>
            <form action="{% url 'integratedTest:viewConfig' instance.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="viewConfig" style="width:100">    
            </form>
        </tr>
        <tr>
            <form action="{% url 'integratedTest:editConfig' instance.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="editConfig" style="width:100">    
            </form>
        </tr>
            {% if data_inst and data_inst.project_name %}
            <tr><form action="{% url 'integratedTest:selTestSet' instance.id %}" method="post">
                {% csrf_token %}
                    <input type="submit" value="selectTestSet" style="width:100">    
                </form>
            </tr>
            {% endif %}
            
            {% if data_inst and data_inst.project_name %}
            <tr><form action="{% url 'integratedTest:selBranch' instance.id %}" method="post">
                {% csrf_token %}
                    <input type="submit" value="selectBranch" style="width:100" 
                        title="A bit slow. Need 10 seconds or more.">    
                </form></tr>
            {% endif %}
        <tr>
            <form action="{% url 'integratedTest:cloneInstance' instance.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Clone" style="width:100">    
            </form></tr><tr>
            <form action="{% url 'integratedTest:deleteInstance' instance.id%}" method="post">
            {% csrf_token %}            
                <input type="submit" value="Delete" style="width:100">    
            </form></tr>
        </table>
        </td>
        <td>{{ instance.name }}</td>
        <td >
            {{ instance.testsuite }}        
        </td>
        {% if instance.progress == 0 %}
            <td class="progress_0" title="{{instance.progress}}"></progress></td>
        {% else %}
            <td class="progress" title="{{instance.progress}}"></progress></td>
        {% endif %}
        <td>{{ instance.test_result }} </td>
        <td><a href="{% url 'integratedTest:viewReport' instance.id%}">Report</a></td>
        <td><a href="{% url 'integratedTest:scheduler' instance.id%}">Scheduler</a></td>
        <td>{{ instance.last_run }}</td>
        <td>{{ instance.created_by }}</td>
        <td>{{ instance.create_datetime }}</td> 
        {% if data_inst.inst_meta %}
         <td>
        {% for key, list in data_inst.inst_meta.items %}
            {% if key == instance.id%}
                {% for value in list %}
                    <b>project</b>:{{ value.project_name }}<br><b>module</b>:{{ value.module_name }}<br><b>server</b>:<br>{{ value.gitserver }}<br><b>branch:</b>{{ value.branch }}<br><b>TestSet:</b>{{ value.TestSet }}<br><br>
                {% endfor %}                
            {% endif %}
        {% endfor %}
         </td>
        {% endif %}
        </tr>
    {% endfor %}
  {% else %}
    <tr>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>  
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
    </tr>
  {% endif %}    
</table>       
</div>

<hr width=20px></hr>
<hr width=20px></hr>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="{% static "jquery.circle-progress.js" %}"></script>
<script>
    jQuery(function($) {
        valuePro = parseInt($('.progress').attr("title"))
        
        $('.progress_0').circleProgress({	
            max: 100,
            fill: {
              gradient: ["red", "orange"]
            },
            value: 100,	
            textFormat:"percent",    
        });
        $('.progress').circleProgress({	
            max: 100,
            fill: {
              gradient: ["red", "orange"]
            },
            value: valuePro,	
            textFormat:"percent",    
        });
    });
</script>

integratedTest/templates/integratedTest/navigator/projects.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">

{% include "integratedTest/navigation.html" %}

<div class="main" style="overflow-x:auto;">
<br>
<table>
  <tr>
    <h4 class="tooltiptext">Project List</h4>
    <div>
        <form action="{% url 'integratedTest:addProject' %}" method="post">
        {% csrf_token %}
            <input type="submit" value="AddProject" style="width:100">    
        </form>
        <hr width=20px></hr>
    </div>
    <th>Actions</th>
    <th>Project Name</th>
    <th>Module List</th>   
    <th>CreatedOn</th>
    <th>CreatedBy</th>
  </tr>
  {% if proj_list %}
  {% for proj in proj_list %}
    <tr>    
        <td>
        
        <hr width=10px></hr>
        <form action="{% url 'integratedTest:editProject' proj.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Edit" style="width:100">    
        </form>
        <form action="{% url 'integratedTest:cloneProject' proj.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clone" style="width:100">    
        </form>
        <form action="{% url 'integratedTest:deleteProject' proj.id%}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" style="width:100">    
        </form>
        </td>
        <td>
        {{ proj.name }}
        </td>        
        <td>{{ proj.module_list }}</td>
        <td>{{ proj.create_datetime }}</td>
        <td>{{ proj.created_by }}</td>         
    </tr>
    {% endfor %}
  {% else %}
    <tr>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>              
    </tr>
  {% endif %}
  
</table>

<hr width=20px></hr>


</div>

integratedTest/templates/integratedTest/navigator/testcase.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">

{% include "integratedTest/navigation.html" %}

<div class="main" style="overflow-x:auto;">
<br>
<table>
  <tr>
    <h4 class="tooltiptext">Test Case List</h4>
    {% if context and context.error %}        
        <b style="color:red">{{context.error}}</b>        
    {% endif %}
    <div>
        <form action="{% url 'integratedTest:addCase' %}" method="post">
        {% csrf_token %}
            <input type="submit" value="AddCase" style="width:100">    
        </form>
        <hr width=20px></hr>
    </div>
    <th>Action</th>
    <th>Case Name</th>
    <th>Executable</th>
    <th>Parameter List</th>
    <th>Executable Type</th>
    <th>Project Name</th>
    <th>Module</th>
    <th>CreatedOn</th>
    <th>CreatedBy</th>
  </tr>
  {% if TestCase_list %}
  {% for case in TestCase_list %}
    <tr>    
        <td>
        
        <hr width=10px></hr>
        <form action="{% url 'integratedTest:editCase' case.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Edit" style="width:100">    
        </form>
        <form action="{% url 'integratedTest:cloneCase' case.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Clone" style="width:100">    
        </form>
        <form action="{% url 'integratedTest:deleteCase' case.id%}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" style="width:100">    
        </form>
        </td>
        <td>
        {{ case.name }}
        </td>
        <td>{{ case.executable }}</td>
        <td>{{ case.parameter_list }}</td>
        <td>{{ case.executable_type }}</td>
        <td>{{ case.project_name }}</td>
        <td>{{ case.module_name }}</td>        
        <td>{{ case.create_datetime }}</td>
        <td>{{ case.created_by }}</td>    
    </tr>
    {% endfor %}
  {% else %}
    <tr>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>  
        <td>N/A</td>
        <td>N/A</td>         
    </tr>
  {% endif %}
  
</table>

<hr width=20px></hr>


</div>

integratedTest/templates/integratedTest/navigator/upload.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">

{% include "integratedTest/navigation.html" %}
<br><br>
{% if documents %}
        <ul>
        {% for document in documents %}
            <li>{{ document.docfile.name }}</li>
        <form action="{% url 'integratedTest:uploadviewf' %}" method="post">
            {% csrf_token %}            
            <input type="submit" value="view">  
            <input type="hidden" id="id_file_path" name="file_path" value="{{document.docfile.path}}">
        </form>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'integratedTest:upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
            <label for="id_project_name">Project Name:</label>
            <select name="project_name" id="id_project_name" >  
            {%for item in projnames %}
              {%if item == name_0 %}
                <option value={{item}} selected>{{item}}</option>
              {%else%}
                <option value={{item}}>{{item}}</option>      
              {%endif%}
            {%endfor%}
          </select>
        </form>
<p style="margin-left:5em;">
{% if file_content %}

    {%for line in file_content %}
        <p leftmargin=50pt>{{line}}</p>
    {%endfor%}
 
{% endif %}
</p>